fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "epel": "git://github.com/stahnma/puppet-module-epel.git"
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    "opsview_server": "#{source_dir}"
